errors = {
    0: "No error",
    1: "Parameter syntax error",
    2: "Unknown command",
    3: "Command length out of limits or command buffer overrun",
    4: "Error while scanning",
    5: "Unallowable move attempted on unreferenced axis, or move attempted with servo off",
    6: "Parameter for SGA not valid",
    7: "Position out of limits",
    8: "Velocity out of limits",
    9: "Attempt to set pivot point while U,V and W not all 0",
    10: "Controller was stopped by command",
    11: "Parameter for SST or for one of the embedded scan algorithms out of range",
    12: "Invalid axis combination for fast scan",
    13: "Parameter for NAV out of range",
    14: "Invalid analog channel",
    15: "Invalid axis identifier",
    16: "Invalid stage name",
    17: "Parameter out of range",
    18: "Invalid macro name",
    19: "Error while recording macro",
    20: "Macro not found",
    21: "Axis has no brake",
    22: "Axis identifier specified more than once",
    23: "Illegal axis or channel",
    24: "Incorrect number of parameters",
    25: "Invalid floating point number",
    26: "Parameter missing",
    27: "Soft limit out of range",
    28: "No manual pad found",
    29: "No more step-response values",
    30: "No step-response values recorded",
    31: "Axis has no reference sensor",
    32: "Axis has no limit switch",
    33: "No relay card installed",
    34: "Command not allowed for selected stage(s)",
    35: "No digital input installed",
    36: "No digital output configured",
    37: "No more MCM responses",
    38: "No MCM values recorded",
    39: "Controller number invalid",
    40: "No joystick configured",
    41: "Invalid axis for electronic gearing, axis can not be slave",
    42: "Position of slave axis is out of range",
    43: "Slave axis cannot be commanded directly when electronic gearing is enabled",
    44: "Calibration of joystick failed",
    45: "Referencing failed",
    46: "OPM (Optical Power Meter) missing",
    47: "OPM (Optical Power Meter) not initialized or cannot be initialized",
    48: "OPM (Optical Power Meter) Communication Error",
    49: "Move to limit switch failed",
    50: "Attempt to reference axis with referencing disabled",
    51: "Selected axis is controlled by joystick",
    52: "Controller detected communication error",
    53: "Command is not allowed while the affected axis is in motion.",
    54: "Unknown parameter",
    55: "No commands were recorded with REP",
    56: "Password invalid",
    57: "Data recorder table does not exist",
    58: "Source option does not exist; number too low or too high",
    59: "Source ID (channel or axis) too low or too high",
    60: "Protected Param: current Command Level (CCL) too low",
    61: "Command execution not possible while Autozero is running",
    62: "Autozero requires at least one linear axis",
    63: "Initialization still in progress",
    64: "Parameter is read-only",
    65: "Parameter not found in non-volatile memory",
    66: "Voltage out of limits",
    67: "Not enough memory available for requested wave curve",
    68: "Not enough memory available for DDL table; DDL can not be started",
    69: "Time delay larger than DDL table; DDL can not be started",
    70: "The requested arrays have different lengths; query them separately",
    71: "Attempt to restart the generator while it is running in single step mode",
    72: "Motion commands and wave generator activation are not allowed when analog target is active",
    73: "Motion commands are not allowed when wave generator output is active; use WGO to disable generator output",
    74: "No sensor channel or no piezo channel connected to selected axis (sensor and piezo matrix)",
    75: "Generator started (WGO) without having selected a wave table (WSL).",
    76: "Interface buffer did overrun and command couldn't be received correctly",
    77: "Data Record Table does not hold enough recorded data",
    78: "Data Record Table is not configured for recording",
    79: "Open-loop commands (SVA, SVR) are not allowed when servo is on",
    80: "Hardware error affecting RAM",
    81: "Not macro command",
    82: "Macro counter out of range",
    83: "Joystick is active",
    84: "Motor is off",
    85: "Macro-only command",
    86: "Invalid joystick axis",
    87: "Joystick unknown",
    88: "Move without referenced stage",
    89: "Command not allowed in current motion mode",
    90: "No tracing possible while digital IOs are used on this HW revision. Reconnect to switch operation mode.",
    91: "Move not possible, would cause collision",
    92: "Stage is not capable of following the master. Check the gear ratio(SRA).",
    93: "This command is not allowed while the affected axis or its master is in motion.",
    94: "Servo cannot be switched on when open-loop joystick control is enabled.",
    95: "This parameter cannot be changed in current servo mode.",
    96: "Unknown stage name",
    97: "Invalid length of value (too much characters)",
    98: "AutoZero procedure was not successful",
    99: "Sensor voltage is off",
    100: "PI LabVIEW driver reports error. See source control for details.",
    200: "No stage connected to axis",
    201: "File with axis parameters not found",
    202: "Invalid axis parameter file",
    203: "Backup file with axis parameters not found",
    204: "PI internal error code 204",
    205: "SMO with servo on",
    206: "uudecode: incomplete header",
    207: "uudecode: nothing to decode",
    208: "uudecode: illegal UUE format",
    209: "CRC32 error",
    210: "Illegal file name (must be 8-0 format)",
    211: "File not found on controller",
    212: "Error writing file on controller",
    213: "VEL command not allowed in DTR Command Mode",
    214: "Position calculations failed",
    215: "The connection between controller and stage may be broken",
    216: "The connected stage has driven into a limit switch, some controllers need CLR to resume operation",
    217: "Strut test command failed because of an unexpected strut stop",
    218: "While MOV! is running position can only be estimated!",
    219: "Position was calculated during MOV motion",
    220: "FIFO buffer underrun during interpolation",
    221: "FIFO buffer overflow during interpolation",
    230: "Invalid handle",
    231: "No bios found",
    232: "Save system configuration failed",
    233: "Load system configuration failed",
    301: "Send buffer overflow",
    302: "Voltage out of limits",
    303: "Open-loop motion attempted when servo ON",
    304: "Received command is too long",
    305: "Error while reading/writing EEPROM",
    306: "Error on I2C bus",
    307: "Timeout while receiving command",
    308: "A lengthy operation has not finished in the expected time",
    309: "Insufficient space to store macro",
    310: "Configuration data has old version number",
    311: "Invalid configuration data",
    333: "Internal hardware error",
    400: "Wave generator index error",
    401: "Wave table not defined",
    402: "Wave type not supported",
    403: "Wave length exceeds limit",
    404: "Wave parameter number error",
    405: "Wave parameter out of range",
    406: "WGO command bit not supported",
    500: "The 'red knob' is still set and disables system",
    501: "The 'red knob' was activated and still disables system - reanimation required",
    502: "Position consistency check failed",
    503: "Hardware collision sensor(s) are activated",
    504: "Strut following error occurred, e.g. caused by overload or encoder failure",
    505: "One sensor signal is not valid",
    506: "Servo loop was unstable due to wrong parameter setting and switched off to avoid damage.",
    507: "digital connection to external spi slave device is lost",
    508: "Move attempt not permitted due to customer or limit settings",
    509: "Emergency stop caused by trigger input",
    530: "A command refers to a coordinate system that does not exist",
    531: "A command refers to a coordinate system that has no parent node",
    532: "Attempt to delete or change a coordinate system that is in use",
    533: "Definition of a coordinate system is cyclic",
    536: "Coordinate system cannot be defined as long as Hexapod is in motion",
    537: "Coordinate system type is not intended for manual enabling",
    539: "A coordinate system cannot be linked to itself",
    540: "Coordinate system definition is erroneous or not complete (replace or delete it)",
    542: "The coordinate systems are not part of the same chain",
    543: "Unused coordinate system must be deleted before new coordinate system can be stored",
    544: "With this coordinate system type SPI usage is not supported",
    545: "Soft limits invalid due to changes in coordinate system",
    546: "Coordinate system is write protected",
    547: "Coordinate system cannot be changed because its content is loaded from a configuration file",
    548: "Coordinate system may not be linked",
    549: "A KSB-type coordinate system can only be rotated by multiples of 90 degrees",
    551: "This query is not supported for this coordinate system type",
    552: "This combination of work and tool coordinate systems does not exist",
    553: "The combination must consist of one work and one tool coordinate system",
    554: "This coordinate system type does not exist",
    555: "BasMac: unknown controller error",
    556: "No coordinate system of this type is enabled",
    557: "Name of coordinate system is invalid",
    558: "File with stored CS systems is missing or erroneous",
    559: "File with leveling CS is missing or erroneous",
    601: "Not enough memory",
    602: "Hardware voltage error",
    603: "Hardware temperature out of range",
    604: "Position error of any axis in the system is too high",
    606: "Maximum value of input signal has been exceeded",
    607: "Value is not integer",
    608: "Fast alignment process cannot be paused because it is not running",
    609: "Fast alignment process cannot be restarted/resumed because it is not paused",
    650: "Parameter could not be set with SPA - SEP needed?",
    651: "Phase finding error",
    652: "Sensor setup error",
    653: "Sensor communication error",
    654: "Motor amplifier error",
    655: "Overcurrent protection triggered by I2T-module",
    656: "Overcurrent protection triggered by amplifier module",
    657: "Safety stop triggered",
    658: "Sensor off?",
    700: "Command not allowed in external mode",
    710: "External mode communication error",
    715: "Invalid mode of operation",
    716: "Firmware stopped by command (#27)",
    717: "External mode driver missing",
    718: "Missing or incorrect configuration of external mode",
    719: "External mode cycletime invalid",
    720: "Brake is activated",
    725: "Drive state transition error",
    731: "Command not allowed while surface detection is running",
    732: "Last surface detection failed",
    733: "Fieldbus is active and is blocking GCS control commands",
    1000: "Too many nested macros",
    1001: "Macro already defined",
    1002: "Macro recording not activated",
    1003: "Invalid parameter for MAC",
    1004: "Deleting macro failed",
    1005: "Controller is busy with some lengthy operation (e.g. reference move, fast scan algorithm)",
    1006: "Invalid identifier (invalid special characters, ...)",
    1007: "Variable or argument not defined",
    1008: "Controller is (already) running a macro",
    1009: "Invalid or missing operator for condition. Check necessary spaces around operator.",
    1010: "No answer was received while executing WAC/MEX/JRC/...",
    1011: "Command not valid during macro execution",
    1012: "Error occured during macro execution",
    1024: "Motion error: position error too large, servo is switched off automatically",
    1025: "Maximum motor output reached",
    1063: "User Profile Mode: Command is not allowed, check for required preparatory commands",
    1064: "User Profile Mode: First target position in User Profile is too far from current position",
    1065: "Controller is (already) in User Profile Mode",
    1066: "User Profile Mode: Block or Data Set index out of allowed range",
    1071: "User Profile Mode: Out of memory",
    1072: "User Profile Mode: Cluster is not assigned to this axis",
    1073: "Unknown cluster identifier",
    1090: "There are too many open tcpip connections",
    2000: "Controller already has a serial number",
    4000: "Sector erase failed",
    4001: "Flash program failed",
    4002: "Flash read failed",
    4003: "HW match code missing/invalid",
    4004: "FW match code missing/invalid",
    4005: "HW version missing/invalid",
    4006: "FW version missing/invalid",
    4007: "FW update failed",
    4008: "FW Parameter CRC wrong",
    4009: "FW CRC wrong",
    5000: "PicoCompensation scan data is not valid",
    5001: "PicoCompensation is running, some actions can not be executed during scanning/recording",
    5002: "Given axis can not be defined as PPC axis",
    5003: "Defined scan area is larger than the travel range",
    5004: "Given PicoCompensation type is not defined",
    5005: "PicoCompensation parameter error",
    5006: "PicoCompensation table is larger than maximum table length",
    5100: "Common error in Nexline firmware module",
    5101: "Output channel for Nexline can not be redefined for other usage",
    5102: "Memory for Nexline signals is too small",
    5103: "RNP can not be executed if axis is in closed loop",
    5104: "relax procedure (RNP) needed",
    5200: "Axis must be configured for this action",
    5300: "Frequency analysis failed",
    5301: "Another frequency analysis is running",
    6000: "Invalid preset value of absolute sensor",
    6001: "Error while writing to sensor",
    6002: "Error while reading from sensor",
    6003: "Checksum error of absolute sensor",
    6004: "General error of absolute sensor",
    6005: "Overflow of absolute sensor position",
}
